class OrdersController < ApplicationController

  # HTTP GET for new order form, the form is generated by the Braintree API javascript
  def new
    # Generate a new client token to be sent to braintree for authentication
    @client_token = Braintree::ClientToken.generate
  end

  # HTTP POST for creating a new order
  def create
  # Receiving payment nonce from braintree servers once the client token was authenticated
  nonce = params[:payment_method_nonce]
  # Generate result only if the nonce is successfully authenticated
  render action: :new and return unless nonce
  # Create braintree transaction using the nonce as a parameter
  result = Braintree::Transaction.sale(
    amount: "10.00",
    payment_method_nonce: nonce
  )

  # If the transcation was successfull, redirect back to application and update user status as having made a payment
  if result.success?
    flash[:notice] = "Payment Successfull"
    current_user.has_paid = true
    current_user.save
    redirect_to new_application_path
  else
    flash[:alert] = "Something is amiss. #{result.transaction.processor_response_text}" unless result.success?
    render 'new'
  end

  end
end
