class User < ActiveRecord::Base

  # Model for a student. Named as User in the source code because it was auto generated by Devise as the root "User"
  # Student has one application which consists of many course applications, also has one referee

  # Assocications
  has_one :application, dependent: :destroy
  belongs_to :referee

  # Devise options
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Validations
  # Uncomment for production. These validations are turned off to make testing easier
  #validates :personal_statement, length: { maximum: 5000 }
  #validates :forename, presence: true
  #validates :surname, presence: true
  #validates :perm_address, presence: true
  #validates :perm_postcode, presence: true
  #validates :phone_no, presence: true
  #validates :fee_payment, presence: true
  #validates :highest_qualification_level, presence: true
  #validates :highest_qualification_institution, presence: true
  #validates :highest_qualification_institution, presence: true
  #validates :referee, presence: true

end
